version: 2

jobs:
    build:
        docker:
            -
                image: circleci/golang:1.11

        working_directory: /go/src/github.com/banzaicloud/banzai-cli

        steps:
            - checkout

            -
                restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

            -
                restore_cache:
                    name: Restore dependencies
                    keys:
                        - gopkg-v1-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
                        - gopkg-v1-{{ .Branch }}
                        - gopkg-v1-master
                        - gopkg-v1

            -
                run:
                    name: Install dependencies
                    command: make vendor

            -
                save_cache:
                    name: Save dependencies
                    key: gopkg-v1-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
                    paths:
                        - vendor/

            -
                restore_cache:
                    name: Restore license cache
                    keys:
                        - licensei-v1-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
                        - licensei-v1-{{ .Branch }}
                        - licensei-v1-master
                        - licensei-v1

            -
                run:
                    name: Download license information for dependencies
                    command: make license-cache

            -
                save_cache:
                    name: Save license cache
                    key: licensei-v1-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
                    paths:
                        - .licensei.cache

            -
                run:
                    name: Check dependency licenses
                    command: make license-check

            -
                run:
                    name: Build
                    command: make build

            -
                run:
                    name: Run linter
                    command: make lint

            -
                run:
                    name: Run tests
                    command: GOARGS="-p=2" make test

            -
                save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/

            -
                persist_to_workspace:
                    root: .
                    paths:
                        - vendor/

            -
                store_test_results:
                    path: build/test_results/
            -
                store_artifacts:
                    path: build/

    frontend-build:
        docker:
            -
                image: circleci/node:11

        steps:
            - checkout

            -
                restore_cache:
                    name: Restore dependencies
                    keys:
                        - npm-v1-{{ .Branch }}-{{ checksum "internal/cli/command/form/web/package-lock.json" }}
                        - npm-v1-{{ .Branch }}
                        - npm-v1-master
                        - npm-v1

            -
                run:
                    name: Build assets
                    command: make client-build

            -
                save_cache:
                    name: Save dependencies
                    key: npm-v1-{{ .Branch }}-{{ checksum "internal/cli/command/form/web/package-lock.json" }}
                    paths:
                        - internal/cli/command/form/web/node_modules/

            -
                persist_to_workspace:
                    root: .
                    paths:
                        - internal/cli/command/form/web/dist/

    release:
        docker:
            -
                image: circleci/golang:1.11

        working_directory: /go/src/github.com/banzaicloud/banzai-cli

        steps:
            - checkout

            -
                attach_workspace:
                    at: .

            -
                run:
                    name: Bundle assets
                    command: make client-bundle

            -
                run:
                    name: Release
                    command: make release

workflows:
    version: 2
    build:
        jobs:
            -
                build:
                    filters:
                        tags:
                            only: /^v?\d+\.\d+\.\d+(-\S*)?$/
            -
                frontend-build:
                    filters:
                        tags:
                            only: /^v?\d+\.\d+\.\d+(-\S*)?$/
                        branches:
                            ignore: /.*/
            -
                release:
                    requires:
                        - build
                    filters:
                        tags:
                            only: /^v?\d+\.\d+\.\d+(-\S*)?$/
                        branches:
                            ignore: /.*/
